GET https://addons-ecs.forgesvc.net/api/addon/228832/file/2645992
User-Agent: Launcher (https://github.com/bhopahk/launcher)

### Guide API file

GET https://addons-ecs.forgesvc.net/api/addon/269708/file/2697844
User-Agent: Launcher (https://github.com/bhopahk/launcher)

### ATM 3 Default File

GET https://addons-ecs.forgesvc.net/api/addon/269708/files
User-Agent: Launcher (https://github.com/bhopahk/launcher)

### ATM 3 Default File

GET https://addons-ecs.forgesvc.net/api/minecraft/version/1.12.2
User-Agent: Launcher (https://github.com/bhopahk/launcher)

###

GET https://addons-ecs.forgesvc.net/api/minecraft/version
User-Agent: Launcher (https://github.com/bhopahk/launcher)

###

GET https://addons-ecs.forgesvc.net/api/addon/269708/files
User-Agent: Launcher (https://github.com/bhopahk/launcher)

### ATM 3 Default File

